#
# Commands:
#   hubot tell me a phrase


phrases = ["Fantasia sexual é que nem cheiro de cocô: a gente só acha normal quando é da gente.",
"Inglêiz eu não sei, maiz heim portuguêiz eu çôu fera",
"O mundo precisa de mais gênios humildes! Hoje em dia somos poucos...",
"É melhor duas abelhas voando do que uma na mão",
"Se você não pode ajudar, atrapalhe! O importante é participar!",
"Macho que é macho pega mulher feia; porque mulher bonita todo mundo quer pegar!",
"Onde quer que você esteja, você sempre estará lá!",
"A humanidade está perdendo seus maiores gênios... Aristóteles faleceu, Newton bateu as botas, Einstein morreu, e eu não estou passando muito bem hoje",
"Quando alguém lhe chamar de gordo não ligue, você é maior que tudo isso",
"Quando um não quer, dois não brigam, mas um apanha",
"Mulher de amigo meu é que nem travesseiro: só ponho a cabeça.",
"Nas horas difíceis da vida, você deve levantar a cabeça, estufar o peito e dizer de boca cheia: Agora fudeu!!!",
"Existem duas maneiras de tratar as mulheres. Até hoje ninguém descobriu quais são.",
"12 de junho é o dia dos namorados; os outros 364 são nossos.... ",
"Quem cedo madruga passa o dia com sono.",
"Extra! Extra! Gêmeo tenta se suicidar e mata o irmão por engano.",
"Canela: dispositivo para se encontrar móveis no escuro",
"Evite acidentes. Faça de propósito",
"O que o instrutor da escola de kamikazes disse para os alunos? -Prestem atenção que vou fazer só uma vez.",
"É chato ser bonito. Mas é muito mais chato ser feio.",
"Se você sorri, eu dou risada com você, se você chora, eu choro com você, se você se joga de baixo de um ônibus vou sentir sua falta.",
"Os velhos costumam dar conselhos porque já perderam a capacidade de dar maus exemplos.",
"Se um dia te der vontade de trabalhar, sente-se e espere que logo passa.",
"A mentira é uma verdade que se esqueceu de acontecer",
"Afogamento é uma coisa que deixa a gente com água na boca",
"Por maior que seja o buraco em que você se encontra, pense que por enquanto, ainda não há terra em cima",
"Se alguém lhe jogar uma pedra, mostre que você é diferente, jogue um tijolo!",
"Eu queria morrer igual ao meu avô, dormindo bem tranquilo... e não gritando desesperadamente, como os 40 passageiros do ônibus que ele dirigia",
"Deus dai me paciência para aguentar meu chefe, porque se me der força eu bato nele!",
"O amor é como capim: você planta, ele cresce... aí vem uma vaca e acaba com tudo!",
"Quando as luzes estão apagadas, todas as mulheres são bonitas.",
"Um aposentado tem entre as pernas outro aposentado.",
"Peido é um telegrama que vem avisar que atrás vem merda.",
"Peido foi o último esforço que o diabo fez para ver se o cú falava.",
"Não confundir espingarda de caçar rolinhas com espinafre de caçarolinha.",
"Não confundir Capitão de fragata com cafetão de gravata.",
"Conversa entre dois tobogans: Como os anus passam depressa.",
"Mulher de amigo meu é que nem violino: Eu viro a cara e meto a vara!",
"Coração de mulher é igual circo, sempre tem lugar pra mais um palhaço.",
"O povo diz quem tem boca vai a Roma, pois o fogão lá da minha casa tem seis bocas e nunca saiu da cozinha.",
"Está constatado na Bíblia. O homem mais feliz do mundo foi Adão, porque foi o único que não possuiu sogra.",
"Homem deve ser tratado como um bom vinho: no escuro, na horizontal, e com rolha na boca.",
"Homem é igual a orelhão: 80% não funciona e o resto está ocupado.",
"Só dou carona a quem me dá.",
"De nada adianta ter barriga de tanquinho se a torneira não funciona.",
"Amigo é igual parafuso: a gente só vê é bom na hora do aperto.",
"Depois dos 40 anos, a única coisa com gordura que o médico deixa um homem comer é a sua própria mulher.",
"O casamento é o método mais caro de se ter uma mulher de graça.",
"Eu bebo para dormir e acordo para beber.",
"Mais vale chegar atrasado neste mundo do que adiantado no outro...",
"Você nasce sem pedir e morre sem querer. Aproveite o intervalo!",
"Numa coisa homens e mulheres concordam: ambos não confiam em mulheres.",
"Se o pássaro João-de-barro cagasse barro, meu pai fazia tijolo.",
"Fiado é igual a barba, se não cortar só cresce.",
"Mulher de amigo meu é que nem cebola: Eu como chorando.",
"Eu não quero um príncipe, eu quero um homem que seja capaz de cativar meu coração sem eu ter que me esforçar pra gostar dele.",
"Você não foi o homem que eu pedi a Deus, mas foi o melhor que ele me deu.",
"Só existem dois tipos de mulheres, as que me amam, ou as que ainda não me conhecem.",
"As nuvens são como chefes...Quando desaparecem, o dia fica lindo.",
"Mais vale um amigo cachorro do que dois amigos bambi. Dito popular na Macholândia",
"Um amigo de verdade não é aquele que separa uma briga, mas sim, aquele que já chega dando voadora.",
"Promoção: Peça Fiado e ganhe um NÃO!!!",
"Se for dirigir não beba, se for beber me chame!!!",
"24 horas num dia, 24 cervejas numa caixa. Coincidência?",
"Quando li sobre os problemas que a bebida causa, deixei de ler.",
"Coma merda! Milhões de moscas não podem estar erradas...",
"Se um dia você sentir um vazio em você, coma que é fome!!!",
"As mulheres perdidas são as mais procuradas.",
"O que há de comum entre um bolo queimado, cerveja estourada e mulher grávida??? Nada, mas se você tivesse tirado antes, nada disso teria acontecido...",
"Se homossexualismo fosse normal, Deus teria criado Adão e Ivo.",
"Beijo não mata a fome, mas abre o apetite...",
"Mulheres são como traduções: as boas não são fiéis e as fiéis não são boas...",
"Sogra é como onça: todos temos que preservar, mas ninguém quer ter em casa.",
"Mulher feia é igual a ventania, só quebra galho.",
"Em dia de tempestades e trovoadas, o local mais seguro é perto da sogra, não há raio que a parta!!!",
"O duro não é carregar o peso do chifre... é sustentar a vaca.",
"Eu bebo pra ficar ruim mesmo, porque se fosse pra ficar bom, eu tomava remédio!",
"O chifre é como o consórcio...quando você menos espera é contemplado!",
"Casar é trocar a admiração de várias mulheres, pela crítica de uma só!!",
"Nas horas difíceis da vida, você deve levantar a cabeça, estufar o peito e dizer de boca cheia: Agora fudeu!!!",
"Não ria de tudo, pois quem acha tudo gozado, é faxineira de motel...",
"Se sua sogra é uma jóia, nós temos a caixinha perfeita! Funerária Vá com Deus",
"A mulher mais feliz do mundo é a namorada do Saci, pois ela sabe que se levar um pé na bunda, quem cai é ele.",
"Eu bebo pouco, mas este pouco me transforma em outra pessoa; e essa outra pessoa bebe pra caralho!!!",
"O Brasil é um país geométrico.... tem problemas angulares, discutidos em mesas redondas, por um monte de bestas quadradas.",
"Para que levar a vida a sério, se nós nascemos duma gozada??!!!",
"Gaúcho que é gaúcho não navega na internet; atravessa a nado!",
"O assaltante pede seu dinheiro ou sua vida; as mulheres querem os dois.",
"Um homem de sucesso é o que ganha mais dinheiro do que sua mulher consegue gastar. Uma mulher de sucesso é a que consegue encontrar um homem desses.",
"Sexo não tem nada a ver com amor. Tanto isso é verdade que o governo me fode há 51 anos e eu não sou apaixonado por ele...",
"Mulher gorda é que nem Ferrari: quando sobe na balança vai de zero a cem em um segundo...",
"Quando você passar na rua e ficarem te olhando, não se sinta o máximo... O feio e o ridículo também chamam a atenção..",
"Aprenda uma coisa: o mundo não gira em torno de você. Só quando você bebe demais.",
"Se um dia a vida lhe der as costas, passe a mão na bunda dela.",
"Todo mundo tem cliente. Só traficante e analista de sistemas é que tem usuário.",
"Os psiquiatras dizem que uma em cada quatro pessoas tem alguma deficiência mental. Fique de olho em três dos seus amigos. Se eles parecerem normais, o retardado é você!!",
"Otário não é aquele que envia ou recebe SPAM, mas sim, quem os responde...",
"Simpático Stress é o espaço de tempo entre uma pescaria e outra.",
"As mulheres são como vinho: com o passar dos anos, umas refinam, outras azedam. E as que azedam, é por falta de rolha.",
"Alguns homens amam tanto suas mulheres, que para não as gastarem, preferem usar as dos outros.",
"As nuvens são como chefes... quando desaparecem, o dia fica lindo!",
"Se não puder ajudar, atrapalhe. Afinal, o importante é participar.",
"Se você está se sentindo sozinho, abandonado, achando que ninguém liga para você... atrase um pagamento...",
"Passar a mulher para trás é fácil, difícil é passar adiante!",
"O natal é injusto, o peru morre e a missa é do galo.",
"Se você é feio, pobre, burro e, mesmo assim, tem um monte de mulher dando em cima de você, só tem uma explicação: Você mora embaixo de um prostíbolo.",
"Parente quando vem pra casa e que nem peixe, passou de três dias começa a feder.",
"Se o mundo fosse bom, bebê não nascia chorando.",
"Estou mais perdido que filho da puta em dia dos pais.",
"Peito de mulher é igual autorama, feito para criança mas só adulto brinca.",
"O casamento, tal como é, é uma coisa estranha, mas afinal de contas, ainda não se achou coisa melhor.",
"O motorista ideal para o Papa-Móvel é o Rubens Barrichello – finalmente ele poderia andar na frente do alemão, dirigindo devagar e com os brasileiros aplaudindo.",
"Não leve a vida tão a sério, afinal, você não vai sair vivo dela mesmo.",
"Solteiro é um sujeito que chega toda manhã ao trabalho vindo de uma direção diferente.",
"Se não andasse de ônibus nos horários de pico, a minha vida sexual seria zero."]

module.exports = (robot) ->
	robot.respond /tell me a phrase/i, (msg) ->
		msg.reply msg.random phrases
